#!/bin/bash

#
# Node.js box for `bxs`
#
# Author: André König <andre.koenig@posteo.de>
#

echo "Installing Node.js 0.12."

apt-get install -y wget libssl-dev python

cd /tmp
wget https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
tar xfz node-v0.12.7.tar.gz && cd node-v0.12.7
./configure
make && make install
